Repository tacosontitan/Mauve, pull requests merged in 2022-09, with the labels that each got.

#13 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#16 Create gitignore
  .gitignore
Labels: documentation

#23 Added WithinRange extension
  Mauve.Tests/Core/Extensibility/IComparableExtensionTests.cs
  Mauve.Tests/Mauve.Tests.csproj
  Mauve/Extensibility/IComparableExtensions.cs
  Mauve/Mauve.csproj
Labels: enhancement

#24 Within Range
  Mauve.Tests/Core/Extensibility/IComparableExtensionTests.cs
  Mauve.Tests/Mauve.Tests.csproj
  Mauve/Extensibility/IComparableExtensions.cs
  Mauve/Mauve.csproj
Labels: enhancement

#26 Updates to documentation.
  CONTRIBUTING.md
  README.md
Labels: documentation

#27 Synchronizing with IR branch.
  CONTRIBUTING.md
  README.md
Labels: documentation

#28 Updating documentation
  CONTRIBUTING.md
  README.md
Labels: documentation

#29 Updating substring branch based on IR
  CONTRIBUTING.md
  README.md
Labels: documentation

#31 Initial release
  README.md
Labels: documentation

#32 Substring queue
  Mauve.Tests/Core/Text/SubstringQueueTests.cs
  Mauve.Tests/Mauve.Tests.csproj
  Mauve/Mauve.csproj
  Mauve/Text/SubstringQueue.cs
Labels: documentation, enhancement, test

#33 Initial release
  Mauve.Tests/Core/Text/SubstringQueueTests.cs
  Mauve.Tests/Mauve.Tests.csproj
  Mauve/Mauve.csproj
  Mauve/Text/SubstringQueue.cs
Labels: documentation, enhancement, test

#35 Mediator
  Mauve.Tests/Core/Extensibility/IEnumerableExtensionTests.cs
  Mauve.Tests/Core/Extensibility/StringExtensionsTests.cs
  Mauve.Tests/Mauve.Tests.csproj
  Mauve/Extensibility/IEnumerableExtensions.cs
  Mauve/Extensibility/StringExtensions.cs
  Mauve/Mauve.csproj
  Mauve/Patterns/Mediator/IMediator.cs
  Mauve/Patterns/Mediator/IMediatorClient.cs
  README.md
  mauve-banner.png
Labels: enhancement

#36 Initial release
  Mauve.Tests/Core/Extensibility/IEnumerableExtensionTests.cs
  Mauve.Tests/Mauve.Tests.csproj
  Mauve/Extensibility/IEnumerableExtensions.cs
  Mauve/Mauve.csproj
  Mauve/Patterns/Mediator/IMediator.cs
  Mauve/Patterns/Mediator/IMediatorClient.cs
Labels: enhancement

#46 Create dotnet.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dotnet.yml
Labels: enhancement, actions

#48 Created string Contains extension to ignore case and a test for it :)
  Mauve.Tests/Core/Extensibility/StringExtensionsTests.cs
  Mauve/Extensibility/StringExtensions.cs
Labels: enhancement, framework

#70 Commented out alert message.
  Mauve.VisualStudio.Community/Commands/Standardize.cs
Labels: 💥 enhancement, 🦄 vs community
